defaults: &defaults
  docker:
    - image: cimg/node:19.5.0

version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    <<: *defaults
    steps:
      - node/install:
          node-version: v16.19.0
          install-yarn: true
      - checkout

workflows:
  version: 2
  test:
    jobs:
      - test
